"""enforce one resume profile per user

Revision ID: 545ada410f56
Revises: e31ac4f79082
Create Date: 2026-07-08 13:42:41.938395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545ada410f56'
down_revision: Union[str, Sequence[str], None] = 'e31ac4f79082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resume_profiles_user_id'), 'resume_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_profiles_user_id'), table_name='resume_profiles')
    # ### end Alembic commands ###
