"""add metadata to job interactions

Revision ID: e0ce7df7fcab
Revises: 545ada410f56
Create Date: 2026-07-10 18:13:45.273828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ce7df7fcab'
down_revision: Union[str, Sequence[str], None] = '545ada410f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interactions', sa.Column('job_location', sa.String(), nullable=True))
    op.add_column('job_interactions', sa.Column('job_work_format', sa.String(), nullable=True))
    op.add_column('job_interactions', sa.Column('job_published_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_interactions', 'job_published_at')
    op.drop_column('job_interactions', 'job_work_format')
    op.drop_column('job_interactions', 'job_location')
    # ### end Alembic commands ###
